title: Jayesh Vasani | Technical Project Manager
description: Technical Project Manager | WordPress | Laravel | Magento | MEAN Stack | SEO Consultant | Driving Success through Effective Project Management & Technical Expertise
